spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 1000
        min-idle: 10
        connection-test-query: select 1
        pool-name: FebsHikariCP
      # 配置默认数据源
      primary: base
      datasource:
        # 数据源-1，名称为 base
        base:
          username: root
          password: SMS@#%&realO914&$#$
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-j6cl03n10izawm6345o.mysql.rds.aliyuncs.com:3306/sms_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
        # 数据源-2，名称为 quartz
        quartz:
          username: root
          password: SMS@#%&realO914&$#$
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-j6cl03n10izawm6345o.mysql.rds.aliyuncs.com:3306/sms_quartz?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
  profiles:
    save-path: /home/sms/logo/
    execl-save-path: /home/sms/upload/
    
  redis:
    # Redis数据库索引（默认为 0）
    database: 3
    # Redis服务器地址
    host: 192.168.1.143
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: 'root2O21O915##'
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000
rocketMQ:
    nameServerAddr: 192.168.1.103:9876;192.168.1.117:9876;192.168.1.151:9876

localIp: 103.156.178.231