server:
  port: 9999
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: prod

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
      
mybatis-plus:
  type-aliases-package: com.hero.sms.*.entity
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty
